import { get, writable } from 'svelte/store';
import { PersonajeModel } from '../models/PersonajeModel';

export const personajeSeleccionado = writable<PersonajeModel[]>([]);

export const personajesStore = writable<PersonajeModel[]>([
  new PersonajeModel(1, 
    "1815-12-10", 
    "1852-11-27", 
    "Ada Lovelace", 
    "Reino Unido", 
    "Considerada la primera programadora de la historia, escribió el primer algoritmo destinado a ser procesado por una máquina.", 
    "https://mujeres360.org/wp-content/uploads/2022/01/image-12.png"),
  new PersonajeModel(2, 
    "1906-06-23", 
    "1992-06-07", 
    "Alan Turing", 
    "Reino Unido", 
    "Padre de la computación moderna, propuso la máquina de Turing y ayudó a descifrar los códigos Enigma durante la Segunda Guerra Mundial.", 
    "https://myhero.com/content/images/thumbs/0123665_alan-turing.jpeg"),
    new PersonajeModel(3, 
    "1903-12-28", 
    "1957-02-08", 
    "John Von Neumann", 
    "Hungaro,Estadounidense", 
    "Fue un matemático, físico y científico computacional húngaro-estadounidense, su trabajo abarcó numerosos campos, como la matemática pura, la física cuántica, la economía, la estadística, la informática, la ingeniería y es considerado uno de los padres de la computación moderna ya que su arquitectura sigue siendo la base de casi todas las computadoras actuales.", 
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSatueEgulf-FMA8fAhfdIUSqcJCfy57q4GRg&s")
 ,new PersonajeModel(4, 
    "1922-07-09", 
    "2022-09-29", 
    "Kathleen Booth", 
    "Británica", 
    "Fue una científica informática británica pionera en el desarrollo de lenguajes ensambladores y una de las primeras personas en programar computadoras. Ayudó a diseñar computadoras británicas como la APE(X)C y escribió el lenguaje ensamblador para ellas, sentando las bases de la programación moderna. También investigó en inteligencia artificial y redes neuronales mucho antes de que fueran populares.",
    "https://cache.legacy.net/legacy/images/cobrands/tribnet/photos/IP0380004-1_20240702.jpgx?w=458&h=499&option=3"
  ),
  new PersonajeModel(5, 
    "1913-06-26", 
    "2010-11-29", 
    "Maurice Wilkes", 
    "Británico", 
    "Fue un científico británico pionero de la computación, conocido por desarrollar la EDSAC (Electronic Delay Storage Automatic Calculator), una de las primeras computadoras electrónicas con programa almacenado. También introdujo el concepto de microprogramación y ayudó a establecer muchas bases de la programación moderna, incluyendo el uso de subrutinas y bibliotecas de software.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR28OhK409F1HXmYwZ4R04dyl89bcDIFIloWQ&s"
    ),
  new PersonajeModel(6,
    "1924-12-03", 
    "2007-03-17", 
    "John Backus", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense reconocido por liderar el desarrollo de FORTRAN, el primer lenguaje de programación de alto nivel ampliamente utilizado. También creó la notación BNF (Backus-Naur Form), que permitió describir formalmente la sintaxis de los lenguajes de programación, siendo clave para el desarrollo de compiladores y lenguajes modernos.",
    "https://www.biografiasyvidas.com/biografia/b/fotos/backus.jpg"
    ),
  new PersonajeModel(7,
    "1927-09-04", 
    "2011-10-24", 
    "John McCarthy", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense considerado uno de los padres de la inteligencia artificial. Inventó el término 'inteligencia artificial' en 1956 y desarrolló el lenguaje de programación LISP, fundamental para el desarrollo de sistemas de IA. Su trabajo sentó las bases teóricas y prácticas de la inteligencia artificial moderna.",
    "https://imagenes.elpais.com/resizer/v2/ONU6VPSB4VG7WPAPRLSULT74XI.jpg?auth=7901c8ac1386dd991fcbd2441edadaa574db78eab3fb4a33fee6175583dd4edc&width=1960&height=1470&smart=true"
    ),
  new PersonajeModel(8,
    "1906-12-09", 
    "1992-01-01", 
    "Grace Hopper", 
    "Estadounidense", 
    "Fue una científica computacional y contraalmirante de la Marina de los Estados Unidos, pionera en la programación. Desarrolló el primer compilador para un lenguaje de programación y participó en la creación de COBOL, uno de los primeros lenguajes de alto nivel. También popularizó el término 'bug' para describir errores en los programas informáticos.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWxgK0aysd1BduMeJ24SyisOk-CqlCSSvhfQ&s"
  ),
  new PersonajeModel(9,
    "1926-05-31", 
    "1992-12-26", 
    "John Kemeny", 
    "Húngaro,Estadounidense", 
    "Fue un matemático y científico computacional húngaro-estadounidense. Es conocido por co-crear el lenguaje de programación BASIC junto a Thomas Kurtz, con el objetivo de facilitar la enseñanza de programación a estudiantes. También fue presidente del Dartmouth College y participó en el desarrollo temprano de sistemas de tiempo compartido.",
    "https://www.azquotes.com/public/pictures/authors/df/1f/df1f81bae1533dbc37ba4d1a199f73fd/54757f5d7c104_john_g_kemeny.jpg"
  ),
  new PersonajeModel(9,
    "1928-02-22", 
    "2024-11-12", 
    "Thomas Kurtz", 
    "Estadounidense", 
    "Es un científico computacional estadounidense reconocido por co-crear el lenguaje de programación BASIC junto a John Kemeny en 1964. Su objetivo era hacer la programación accesible para todos los estudiantes, no solo para científicos. También fue pionero en el desarrollo de sistemas de tiempo compartido y en la promoción de la computación educativa.",
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQlAchdEM3VypeDB0BiGGdSJ86n80toEXmES955PRi06zcQeVrpQaaKIb3NlOil-jyRkvd9ceGaTI7LoYSDgp2JIQ"
  ),
  new PersonajeModel(10,
    "1931-10-12", 
    "2002-06-29", 
    "Ole-Johan Dahl", 
    "Noruego", 
    "Fue un científico computacional noruego considerado uno de los padres de la programación orientada a objetos. Junto a Kristen Nygaard, desarrolló el lenguaje de programación Simula, que introdujo conceptos fundamentales como clases, objetos y herencia, los cuales influyeron directamente en lenguajes modernos como Java, C++ y Python.",
    "https://www.ub.uio.no/fag/informatikk/faglig/dns/bilder/dahlolejohan_cropped.jpeg"
),
  new PersonajeModel(10,
    "1926-08-27", 
    "2002-08-10", 
    "Kristen Nygaard", 
    "Noruego", 
    "Fue un informático noruego pionero en la programación orientada a objetos. Junto a Ole-Johan Dahl, creó el lenguaje de programación Simula en los años 60, el cual introdujo conceptos clave como clases y objetos. Su trabajo fue esencial para la evolución de la informática moderna y la enseñanza de la programación estructurada y orientada a objetos.",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhVw6YVlGjD1TbbSyzuEyXrIrfHdSY0sChZ48bcTBQlXwBskze0YSI-H8EIftQ_ikTP0gdQetssB_Go3jZpVifF9mjHVdlMWKJRglBQ3hiMrX_xJm_0avlxLveECJqIqofgZAgALFFnc5U/s1600/08-27+Efemerides+de+Tecnologia+kristen_nygaard.jpg"
  ),
  new PersonajeModel(11,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense conocido por crear el lenguaje de programación C y por ser uno de los desarrolladores del sistema operativo Unix. Su trabajo sentó las bases de gran parte del software moderno, ya que C influyó en muchos lenguajes posteriores y Unix en los sistemas operativos actuales como Linux y macOS.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(11,
    "1943-02-04", 
    "Aun Esta Vivo con 82 años", 
    "Ken Thompson", 
    "Estadounidense", 
    "Es un científico computacional estadounidense reconocido por ser uno de los creadores del sistema operativo Unix junto a Dennis Ritchie. También desarrolló el lenguaje de programación B, precursor de C, y trabajó en proyectos fundamentales como Plan 9 y Go. Su trabajo ha influido profundamente en el desarrollo de sistemas operativos y lenguajes modernos.",
    "https://twimgs.com/informationweek/1304/304Dobbs_Thompson.jpg"
),
  new PersonajeModel(12,
    "1934-02-15", 
    "2024-01-01", 
    "Niklaus Wirth", 
    "Suizo", 
    "Es un científico computacional suizo conocido por diseñar varios lenguajes de programación influyentes, entre ellos Pascal, Modula y Oberon. Su trabajo se centró en la simplicidad y eficiencia del software, y fue un defensor de la enseñanza estructurada de la programación. Su enfoque ayudó a formar generaciones de programadores y sistemas educativos.",
    "https://www.comp.hkbu.edu.hk/dlecture/wirth/img/niklaus_wirth.jpg"
  ),
  new PersonajeModel(13,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense conocido por crear el lenguaje de programación C y por ser uno de los desarrolladores del sistema operativo Unix. Su trabajo sentó las bases de gran parte del software moderno, ya que C influyó en muchos lenguajes posteriores y Unix en los sistemas operativos actuales como Linux y macOS.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(14,
    "1947-02-08", 
    "Aun Esta Vivo con 78 años", 
    "Gerald Jay Sussman", 
    "Estadounidense", 
    "Es catedrático de Ingeniería Eléctrica del Instituto Tecnológico de Massachusetts. Se licenció y doctoró en matemáticas en el MIT en 1968 y 1973 respectivamente. Ha participado en la investigación sobre inteligencia artificial en el MIT desde 1964",
    "https://i.ytimg.com/vi/Tdwr9tweTDE/maxresdefault.jpg"
  ),
  new PersonajeModel(14,
    "1954-10-02", 
    "Aun Esta Vivo con 71 años", 
    "Guy L. Steele Jr.", 
    "Estadounidense", 
    "Es un destacado científico de la computación estadounidense, conocido por su trabajo en el diseño de lenguajes de programación. Fue co-creador de Scheme (junto a Gerald Jay Sussman) y participó en el desarrollo de otros lenguajes importantes como Java y Common Lisp. También es reconocido por su claridad en la escritura técnica y por contribuir a los estándares de varios lenguajes.",
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT_Ywoq1EYce2xGqPhaVwSJcvAsY9oUu3Z7B1Mb5hM6vgdVN5Vo"
  )
]);

export const seleccionarPersonaje = (IdPersonajes: number[]): void => {
  const personaje: PersonajeModel[] = get(personajesStore);
  personajeSeleccionado.set(personaje.filter(personaje => IdPersonajes.includes(personaje.IdPersonaje)));
};