import { get, writable } from 'svelte/store';
import { PersonajeModel } from '../models/PersonajeModel';

export const personajeSeleccionado = writable<PersonajeModel[]>([]);

export const personajesStore = writable<PersonajeModel[]>([
  new PersonajeModel(1, 
    "1815-12-10", 
    "1852-11-27", 
    "Ada Lovelace", 
    "Reino Unido", 
    "Considerada la primera programadora de la historia, escribió el primer algoritmo destinado a ser procesado por una máquina.", 
    "https://mujeres360.org/wp-content/uploads/2022/01/image-12.png"),
  new PersonajeModel(2, 
    "1906-06-23", 
    "1992-06-07", 
    "Alan Turing", 
    "Reino Unido", 
    "Padre de la computación moderna, propuso la máquina de Turing y ayudó a descifrar los códigos Enigma durante la Segunda Guerra Mundial.", 
    "https://myhero.com/content/images/thumbs/0123665_alan-turing.jpeg"),
    new PersonajeModel(3, 
    "1903-12-28", 
    "1957-02-08", 
    "John Von Neumann", 
    "Hungaro,Estadounidense", 
    "Fue un matemático, físico y científico computacional húngaro-estadounidense, su trabajo abarcó numerosos campos, como la matemática pura, la física cuántica, la economía, la estadística, la informática, la ingeniería y es considerado uno de los padres de la computación moderna ya que su arquitectura sigue siendo la base de casi todas las computadoras actuales.", 
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSatueEgulf-FMA8fAhfdIUSqcJCfy57q4GRg&s")
 ,new PersonajeModel(4, 
    "1922-07-09", 
    "2022-09-29", 
    "Kathleen Booth", 
    "Británica", 
    "Fue una científica informática británica pionera en el desarrollo de lenguajes ensambladores y una de las primeras personas en programar computadoras. Ayudó a diseñar computadoras británicas como la APE(X)C y escribió el lenguaje ensamblador para ellas, sentando las bases de la programación moderna. También investigó en inteligencia artificial y redes neuronales mucho antes de que fueran populares.",
    "https://cache.legacy.net/legacy/images/cobrands/tribnet/photos/IP0380004-1_20240702.jpgx?w=458&h=499&option=3"
  ),
  new PersonajeModel(5, 
    "1913-06-26", 
    "2010-11-29", 
    "Maurice Wilkes", 
    "Británico", 
    "Fue un científico británico pionero de la computación, conocido por desarrollar la EDSAC (Electronic Delay Storage Automatic Calculator), una de las primeras computadoras electrónicas con programa almacenado. También introdujo el concepto de microprogramación y ayudó a establecer muchas bases de la programación moderna, incluyendo el uso de subrutinas y bibliotecas de software.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR28OhK409F1HXmYwZ4R04dyl89bcDIFIloWQ&s"
    ),
  new PersonajeModel(6,
    "1924-12-03", 
    "2007-03-17", 
    "John Backus", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense reconocido por liderar el desarrollo de FORTRAN, el primer lenguaje de programación de alto nivel ampliamente utilizado. También creó la notación BNF (Backus-Naur Form), que permitió describir formalmente la sintaxis de los lenguajes de programación, siendo clave para el desarrollo de compiladores y lenguajes modernos.",
    "https://www.biografiasyvidas.com/biografia/b/fotos/backus.jpg"
    ),
  new PersonajeModel(7,
    "1927-09-04", 
    "2011-10-24", 
    "John McCarthy", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense considerado uno de los padres de la inteligencia artificial. Inventó el término 'inteligencia artificial' en 1956 y desarrolló el lenguaje de programación LISP, fundamental para el desarrollo de sistemas de IA. Su trabajo sentó las bases teóricas y prácticas de la inteligencia artificial moderna.",
    "https://imagenes.elpais.com/resizer/v2/ONU6VPSB4VG7WPAPRLSULT74XI.jpg?auth=7901c8ac1386dd991fcbd2441edadaa574db78eab3fb4a33fee6175583dd4edc&width=1960&height=1470&smart=true"
    ),
  new PersonajeModel(8,
    "1906-12-09", 
    "1992-01-01", 
    "Grace Hopper", 
    "Estadounidense", 
    "Fue una científica computacional y contraalmirante de la Marina de los Estados Unidos, pionera en la programación. Desarrolló el primer compilador para un lenguaje de programación y participó en la creación de COBOL, uno de los primeros lenguajes de alto nivel. También popularizó el término 'bug' para describir errores en los programas informáticos.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWxgK0aysd1BduMeJ24SyisOk-CqlCSSvhfQ&s"
  ),
  new PersonajeModel(9,
    "1926-05-31", 
    "1992-12-26", 
    "John Kemeny", 
    "Húngaro,Estadounidense", 
    "Fue un matemático y científico computacional húngaro-estadounidense. Es conocido por co-crear el lenguaje de programación BASIC junto a Thomas Kurtz, con el objetivo de facilitar la enseñanza de programación a estudiantes. También fue presidente del Dartmouth College y participó en el desarrollo temprano de sistemas de tiempo compartido.",
    "https://www.azquotes.com/public/pictures/authors/df/1f/df1f81bae1533dbc37ba4d1a199f73fd/54757f5d7c104_john_g_kemeny.jpg"
  ),
  new PersonajeModel(9,
    "1928-02-22", 
    "2024-11-12", 
    "Thomas Kurtz", 
    "Estadounidense", 
    "Es un científico computacional estadounidense reconocido por co-crear el lenguaje de programación BASIC junto a John Kemeny en 1964. Su objetivo era hacer la programación accesible para todos los estudiantes, no solo para científicos. También fue pionero en el desarrollo de sistemas de tiempo compartido y en la promoción de la computación educativa.",
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQlAchdEM3VypeDB0BiGGdSJ86n80toEXmES955PRi06zcQeVrpQaaKIb3NlOil-jyRkvd9ceGaTI7LoYSDgp2JIQ"
  ),
  new PersonajeModel(10,
    "1931-10-12", 
    "2002-06-29", 
    "Ole-Johan Dahl", 
    "Noruego", 
    "Fue un científico computacional noruego considerado uno de los padres de la programación orientada a objetos. Junto a Kristen Nygaard, desarrolló el lenguaje de programación Simula, que introdujo conceptos fundamentales como clases, objetos y herencia, los cuales influyeron directamente en lenguajes modernos como Java, C++ y Python.",
    "https://www.ub.uio.no/fag/informatikk/faglig/dns/bilder/dahlolejohan_cropped.jpeg"
),
  new PersonajeModel(10,
    "1926-08-27", 
    "2002-08-10", 
    "Kristen Nygaard", 
    "Noruego", 
    "Fue un informático noruego pionero en la programación orientada a objetos. Junto a Ole-Johan Dahl, creó el lenguaje de programación Simula en los años 60, el cual introdujo conceptos clave como clases y objetos. Su trabajo fue esencial para la evolución de la informática moderna y la enseñanza de la programación estructurada y orientada a objetos.",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhVw6YVlGjD1TbbSyzuEyXrIrfHdSY0sChZ48bcTBQlXwBskze0YSI-H8EIftQ_ikTP0gdQetssB_Go3jZpVifF9mjHVdlMWKJRglBQ3hiMrX_xJm_0avlxLveECJqIqofgZAgALFFnc5U/s1600/08-27+Efemerides+de+Tecnologia+kristen_nygaard.jpg"
  ),
  new PersonajeModel(11,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense conocido por crear el lenguaje de programación C y por ser uno de los desarrolladores del sistema operativo Unix. Su trabajo sentó las bases de gran parte del software moderno, ya que C influyó en muchos lenguajes posteriores y Unix en los sistemas operativos actuales como Linux y macOS.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(11,
    "1943-02-04", 
    "Aun Esta Vivo con 82 años", 
    "Ken Thompson", 
    "Estadounidense", 
    "Es un científico computacional estadounidense reconocido por ser uno de los creadores del sistema operativo Unix junto a Dennis Ritchie. También desarrolló el lenguaje de programación B, precursor de C, y trabajó en proyectos fundamentales como Plan 9 y Go. Su trabajo ha influido profundamente en el desarrollo de sistemas operativos y lenguajes modernos.",
    "https://twimgs.com/informationweek/1304/304Dobbs_Thompson.jpg"
),
  new PersonajeModel(12,
    "1934-02-15", 
    "2024-01-01", 
    "Niklaus Wirth", 
    "Suizo", 
    "Es un científico computacional suizo conocido por diseñar varios lenguajes de programación influyentes, entre ellos Pascal, Modula y Oberon. Su trabajo se centró en la simplicidad y eficiencia del software, y fue un defensor de la enseñanza estructurada de la programación. Su enfoque ayudó a formar generaciones de programadores y sistemas educativos.",
    "https://www.comp.hkbu.edu.hk/dlecture/wirth/img/niklaus_wirth.jpg"
  ),
  new PersonajeModel(13,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un científico computacional estadounidense conocido por crear el lenguaje de programación C y por ser uno de los desarrolladores del sistema operativo Unix. Su trabajo sentó las bases de gran parte del software moderno, ya que C influyó en muchos lenguajes posteriores y Unix en los sistemas operativos actuales como Linux y macOS.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(14,
    "1947-02-08", 
    "Aun Esta Vivo con 78 años", 
    "Gerald Jay Sussman", 
    "Estadounidense", 
    "Es catedrático de Ingeniería Eléctrica del Instituto Tecnológico de Massachusetts. Se licenció y doctoró en matemáticas en el MIT en 1968 y 1973 respectivamente. Ha participado en la investigación sobre inteligencia artificial en el MIT desde 1964",
    "https://i.ytimg.com/vi/Tdwr9tweTDE/maxresdefault.jpg"
  ),
  new PersonajeModel(14,
    "1954-10-02", 
    "Aun Esta Vivo con 71 años", 
    "Guy L. Steele Jr.", 
    "Estadounidense", 
    "Es un destacado científico de la computación estadounidense, conocido por su trabajo en el diseño de lenguajes de programación. Fue co-creador de Scheme (junto a Gerald Jay Sussman) y participó en el desarrollo de otros lenguajes importantes como Java y Common Lisp. También es reconocido por su claridad en la escritura técnica y por contribuir a los estándares de varios lenguajes.",
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT_Ywoq1EYce2xGqPhaVwSJcvAsY9oUu3Z7B1Mb5hM6vgdVN5Vo"
  ),
  new PersonajeModel(15,
    "1940-05-17", 
    "Aun Esta Vivo con 85 anios", 
    "Alan Kay", 
    "Estadounidense", 
    "Es un científico computacional estadounidense pionero en la programación orientada a objetos y en el desarrollo de la interfaz gráfica de usuario. Fue uno de los creadores del lenguaje Smalltalk y visionario del concepto de la computadora personal. Su trabajo influyó en tecnologías modernas como las ventanas, el escritorio y los dispositivos interactivos.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs69fVAskz54mJLtdG_okcgDmeAlZX28B9Nw&s"
  ),
  new PersonajeModel(16,
    "1950-12-30", 
    "Aun Esta Vivo con 74 anios", 
    "Bjarne Stroustrup", 
    "Danés", 
    "Es un científico computacional danés conocido por ser el creador del lenguaje de programación C++, el cual combinó las características del lenguaje C con la programación orientada a objetos. Su trabajo ha sido fundamental para el desarrollo de software de alto rendimiento en sistemas operativos, videojuegos, aplicaciones financieras y más.",
    "https://www.ull.es/portal/noticias/wp-content/uploads/sites/13/2025/02/bjarne-stroustrup.jpeg"
  ),
  new PersonajeModel(17,
    "1954-09-27", 
    "Aun Esta Vivo con 70 anios", 
    "Larry Wall", 
    "Estadounidense", 
    "Es un programador y lingüista estadounidense conocido por crear el lenguaje de programación Perl. Diseñó Perl con el objetivo de facilitar la manipulación de texto y la administración de sistemas. Su enfoque flexible e intuitivo hizo que Perl fuera ampliamente adoptado en bioinformática, desarrollo web y administración de servidores durante los años 90 y 2000.",
    "https://www.perl.com/images/listen-to-larry-wall-s-state-of-the-onion-2000-on-youtube/larry-wall.jpg"
  ),
  new PersonajeModel(18,
    "1956-01-31", 
    "Aun Esta Vivo con 69 anios", 
    "Guido van Rossum", 
    "Neerlandés", 
    "Es un científico computacional neerlandés conocido por ser el creador del lenguaje de programación Python. Diseñó Python con el objetivo de ser simple, legible y fácil de aprender, lo que lo convirtió en uno de los lenguajes más populares del mundo. Su trabajo ha impactado áreas como desarrollo web, ciencia de datos, inteligencia artificial y educación en programación.",
    "https://gvanrossum.github.io/images/guido-headshot-2019.jpg"
  ),
  new PersonajeModel(19,
    "1952-06-03", 
    "Aun Esta Vivo con 73 anios", 
    "Alan Cooper", 
    "Estadounidense", 
    "Es un diseñador de software y programador estadounidense conocido como el 'padre de Visual Basic', ya que desarrolló la herramienta original que Microsoft adoptó y transformó en Visual Basic. Su trabajo facilitó la creación de aplicaciones con interfaces gráficas de forma visual y accesible, y ha sido influyente en el diseño centrado en el usuario en el desarrollo de software.",
    "https://miro.medium.com/v2/resize:fit:2400/1*Wnmk3ItpT_6cKeQUSlc5hg.jpeg"
  ),
  new PersonajeModel(20,
    "1955-05-19", 
    "Aun Esta Vivo con 70 anios", 
    "James Gosling", 
    "Canadiense", 
    "Es un científico computacional canadiense conocido por ser el creador del lenguaje de programación Java. Desarrolló Java en Sun Microsystems con el objetivo de crear un lenguaje multiplataforma, seguro y orientado a objetos. Java se convirtió en uno de los lenguajes más utilizados en el desarrollo de aplicaciones empresariales, móviles y web.",
    "https://www.sis.pitt.edu/mbsclass/hall_of_fame/images/gosling.jpg"
  ),
  new PersonajeModel(21,
    "1961-07-04", 
    "Aun Esta Vivo con 64 anios", 
    "Brendan Eich", 
    "Estadounidense", 
    "Es un programador y tecnólogo estadounidense conocido por ser el creador del lenguaje de programación JavaScript, el cual desarrolló en solo 10 días mientras trabajaba en Netscape. JavaScript se convirtió en una de las tecnologías fundamentales del desarrollo web moderno. También fue cofundador de Mozilla y fundador del navegador Brave.",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Brendan_Eich_Mozilla_Foundation_official_photo.jpg/1200px-Brendan_Eich_Mozilla_Foundation_official_photo.jpg"
),
  new PersonajeModel(22,
    "1968-11-22", 
    "Aun Esta Vivo con 56 anios", 
    "Rasmus Lerdorf", 
    "Groenlandés,Canadiense", 
    "Es un programador groenlandés-canadiense conocido por crear el lenguaje de programación PHP en 1994. Inicialmente desarrollado como un conjunto de scripts para gestionar su página web personal, PHP evolucionó hasta convertirse en uno de los lenguajes más utilizados para el desarrollo web del lado del servidor, impulsando millones de sitios en todo el mundo.",
    "https://pbs.twimg.com/profile_images/918348833205116928/V9ROYRNJ_400x400.jpg"
),
  new PersonajeModel(23,
    "1965-04-14", 
    "Aun Esta Vivo con 60 anios", 
    "Yukihiro Matsumoto", 
    "Japonés", 
    "Es un científico computacional japonés conocido por ser el creador del lenguaje de programación Ruby. Diseñó Ruby con el objetivo de hacer la programación más sencilla y placentera para los desarrolladores, combinando elementos de lenguajes como Perl, Smalltalk y Lisp. Ruby se hizo popular especialmente gracias al framework web Ruby on Rails.",
    "https://siliconangle.com/files/2011/08/matz.jpg"
),
  new PersonajeModel(24,
    "2001", 
    "",
    "Creadores del Manifiesto Ágil", 
    "Diversas nacionalidades", 
    "Fueron 17 expertos en desarrollo de software que se reunieron en 2001 en Snowbird, Utah, para definir un conjunto de valores y principios que dieran lugar al Manifiesto Ágil. Este documento revolucionó la forma en que se desarrollan proyectos de software, promoviendo la colaboración, la flexibilidad, la entrega continua y la respuesta al cambio.",
    "https://cloudfront.codeproject.com/architecture/1064114/000.jpg"
),
  new PersonajeModel(25,
    "1960-12-02", 
    "Aun Esta Vivo con 64 anios", 
    "Anders Hejlsberg", 
    "Danés", 
    "Es un ingeniero de software danés conocido por ser el principal arquitecto del lenguaje de programación C# de Microsoft. También creó el popular lenguaje Turbo Pascal y fue uno de los diseñadores principales de Delphi. Su trabajo ha influido profundamente en el desarrollo de software moderno en plataformas Microsoft y más allá.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Xqw_fCI9vzOM05YxBYhWH60VULyhSHkyA&s"
),
  new PersonajeModel(26,
    "1979-10-15", 
    "Aun Esta Vivo con 45 anios", 
    "David Heinemeier Hansson", 
    "Danés", 
    "Es un programador danés conocido por crear el framework web Ruby on Rails, que revolucionó el desarrollo web al facilitar la construcción rápida y eficiente de aplicaciones. También es cofundador de la plataforma de gestión de proyectos Basecamp y un promotor activo de prácticas de desarrollo ágil y software de calidad.",
    "https://images.squarespace-cdn.com/content/v1/61a2ba6209495b7cde63e740/f0146386-1933-495b-aa8e-97d325a7ec23/David+Heinemeier+Hansson.jpg"
),
  new PersonajeModel(27,
    "1955-02-24", 
    "2011-10-05", 
    "Steve Jobs", 
    "Estadounidense", 
    "Fue un empresario, inventor y magnate estadounidense, cofundador de Apple Inc. Fue una figura clave en la revolución de la computación personal, y también influyó en la industria de la música digital, el cine de animación y los dispositivos móviles con productos icónicos como el Macintosh, iPod, iPhone y iPad.",
    "https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/13873773/stevejobs.1419962519.png?quality=90&strip=all&crop=0,13.457556935818,100,73.084886128364"
),
new PersonajeModel(28,
    "1981-01-22", 
    "Actualmente vivo", 
    "Ryan Dahl", 
    "Estadounidense", 
    "Ryan Dahl es un ingeniero de software estadounidense que desarrolló Node.js en 2009. Estudió Matemáticas en UC San Diego y posteriormente hizo estudios de doctorado en matemáticas. En 2018 fundó Deno, un nuevo runtime más seguro para JavaScript y TypeScript.",
    "https://cdn.cloudinary.com/stichting-frontend-amsterdam/image/upload/v1674813354/dev/Dahl_Ryan_wg0lg5.png"
),
  new PersonajeModel(29,
    "1979-05-27", 
    "Actualmente vivo", 
    "Tom Preston-Werner", 
    "Estadounidense", 
    "Cofundador y primer CEO de GitHub, Preston-Werner ayudó a transformar la forma en que los desarrolladores colaboran, versionan y comparten código, haciendo del código abierto una práctica estándar.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWad4zCbYGj0rjz67xLkzkD5mU6S5bQS0CNw&s"
),
  new PersonajeModel(30,
    "1978-06-30", 
    "Actualmente vivo", 
    "Chris Lattner", 
    "Estadounidense", 
    "Lattner inició el desarrollo de Swift como una alternativa moderna, segura y potente a Objective-C. Apple lo lanzó oficialmente en 2014 y se convirtió en el lenguaje principal para aplicaciones iOS y macOS.",
    "https://www.nondot.org/sabre/img/ChrisPhoto5.jpg"
),
  new PersonajeModel(31,
    "1960-12-02", 
    "Actualmente vivo", 
    "Anders Hejlsberg", 
    "Danés", 
    "Creador de Turbo Pascal y Delphi, Hejlsberg diseñó TypeScript como un superconjunto de JavaScript con tipado estático, mejorando el mantenimiento y escalabilidad de grandes aplicaciones.",
    "https://upload.wikimedia.org/wikipedia/commons/e/ef/Anders_Hejlsberg.jpg"
),
  new PersonajeModel(32,
    "1984-08-05", 
    "Actualmente vivo", 
    "Jordan Walke", 
    "Estadounidense", 
    "Ingeniero de Facebook que creó React.js, una biblioteca que cambió el paradigma del desarrollo frontend mediante componentes reutilizables y un DOM virtual eficiente.",
    "https://media.licdn.com/dms/image/v2/D4E03AQF4wHiGZObs0g/profile-displayphoto-shrink_200_200/B4EZZpHJM1HoAg-/0/1745520203877?e=2147483647&v=beta&t=1uF6EPQD8JW6YETHihWLJ1g5bwlicuQMV17Smqu_mEk"
),
  new PersonajeModel(33,
    "1973", 
    "Actualmente vivo", 
    "Graydon Hoare", 
    "Canadiense", 
    "Hoare comenzó Rust como un proyecto personal, y Mozilla lo patrocinó. Rust ofrece seguridad de memoria sin recolector de basura, y se usa en sistemas embebidos, navegadores y backend de alto rendimiento",
    "https://images.crunchbase.com/image/upload/c_thumb,h_256,w_256,f_auto,g_face,z_0.7,q_auto:eco,dpr_1/ywecf1vqgwj0abhbwskb"
),
  new PersonajeModel(35,
    "1980", 
    "Actualmente vivo", 
    "Luke Wagner", 
    "Estadounidense", 
    "Luke Wagner y el equipo de Mozilla lideraron el desarrollo de WebAssembly, un formato binario portable para ejecutar código de alto rendimiento en el navegador. Ideal para videojuegos, simulaciones y edición multimedia.",
    "https://www.fastly.com/cimages/ocb1q9kflo7k/2xiIWWRVolxPBc40EMvCy6/29ba25f3f237069a5790aa8bd21dd933/image-20240227-202107.png?auto=avif&crop=1:1,smart&width=288"
),
  new PersonajeModel(37,
    "1990", 
    "Actualmente vivo", 
    "Jarred Sumner", 
    "Estadounidense", 
    "Sumner desarrolló Bun como un runtime alternativo a Node.js, más rápido y con herramientas integradas como bundler, test runner y gestor de paquetes. Está escrito en Zig y optimizado para velocidad.",
    "https://pbs.twimg.com/profile_images/1342417825483300864/Vz4ChOFG_400x400.jpg"
),
  new PersonajeModel(38,
    "1980", 
    "Actualmente vivo", 
    "Rich Harris", 
    "Estadounidense", 
    "Estos frameworks combinan frontend y backend en una sola estructura coherente. SvelteKit se enfoca en rendimiento y simplicidad, mientras que Remix prioriza la experiencia del usuario y la optimización SEO desde el servidor.",
    "https://avatars.githubusercontent.com/u/1162160?v=4"
),
  new PersonajeModel(39,
    "", 
    "", 
    "Comunidad open source", 
    "", 
    "Rust y WASM son elegidos para entornos de nube por su seguridad, eficiencia y portabilidad. Se usan cada vez más en microservicios, edge computing y entornos con recursos limitados.",
    "https://cdn.thenewstack.io/media/2021/09/480a814f-rust-wasm.png"
)

]);

export const seleccionarPersonaje = (IdPersonajes: number[]): void => {
  const personaje: PersonajeModel[] = get(personajesStore);
  personajeSeleccionado.set(personaje.filter(personaje => IdPersonajes.includes(personaje.IdPersonaje)));
};