import { get, writable } from 'svelte/store';
import { PersonajeModel } from '../models/PersonajeModel';

export const personajeSeleccionado = writable<PersonajeModel[]>([]);

export const personajesStore = writable<PersonajeModel[]>([
  new PersonajeModel(1, 
    "1815-12-10", 
    "1852-11-27", 
    "Ada Lovelace", 
    "Reino Unido", 
    "Matemática y escritora pionera en el campo de la computación, reconocida por su trabajo con la máquina analítica de Charles Babbage. Su visión revolucionaria permitió concebir el primer algoritmo diseñado para ser ejecutado por una máquina, anticipando conceptos clave de la programación moderna como los ciclos repetitivos. Su legado sentó las bases para el desarrollo de la informática y se ha convertido en un símbolo de inspiración para las mujeres en las ciencias y tecnologías STEM.", 
    "https://mujeres360.org/wp-content/uploads/2022/01/image-12.png"),
  new PersonajeModel(2, 
    "1906-06-23", 
    "1992-06-07", 
    "Alan Turing", 
    "Reino Unido", 
    "Considerado uno de los padres de la informática, sus ideas sentaron las bases teóricas de la computación moderna mediante la creación de la máquina de Turing. Durante la Segunda Guerra Mundial, lideró el equipo que descifró los códigos de la máquina Enigma, acortando significativamente el conflicto. También es referente en inteligencia artificial gracias a la prueba que lleva su nombre, planteando si una máquina puede simular la inteligencia humana. Su vida, marcada por la persecución por su orientación sexual, lo convirtió además en un símbolo de la lucha por los derechos humanos. Su legado sigue presente en la ciencia, la tecnología y la cultura contemporánea.", 
    "https://myhero.com/content/images/thumbs/0123665_alan-turing.jpeg"),
    new PersonajeModel(3, 
    "1903-12-28", 
    "1957-02-08", 
    "John Von Neumann", 
    "Hungaro,Estadounidense", 
    "Pionero en múltiples disciplinas, dejó una huella profunda en la informática al definir la arquitectura de Von Neumann, base de casi todos los computadores modernos. Su enfoque de almacenar instrucciones y datos en la misma memoria revolucionó la programación y facilitó el desarrollo de lenguajes y compiladores. También fue fundador de la teoría de juegos, desarrolló el algoritmo de merge sort y sentó las bases de los autómatas celulares, abriendo paso a conceptos como la vida artificial y la auto-replicación computacional. Su legado abarca desde el hardware hasta la teoría de la computación.", 
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSatueEgulf-FMA8fAhfdIUSqcJCfy57q4GRg&s")
 ,new PersonajeModel(4, 
    "1922-07-09", 
    "2022-09-29", 
    "Kathleen Booth", 
    "Británica", 
    "Pionera en la programación, escribió el primer ensamblador, facilitando el paso del código binario a instrucciones más comprensibles. Programó una de las primeras computadoras electrónicas británicas y desarrolló software para varios de los diseños creados junto a su esposo. Participó en la creación del primer dispositivo de almacenamiento rotatorio y fue autora de uno de los primeros libros sobre programación. También incursionó en la traducción automática de lenguajes y, décadas después, en redes neuronales. Su legado técnico incluye el multiplicador de Booth, aún presente en los procesadores actuales. Fue además cofundadora de uno de los primeros programas universitarios de ciencias de la computación.",
    "https://cache.legacy.net/legacy/images/cobrands/tribnet/photos/IP0380004-1_20240702.jpgx?w=458&h=499&option=3"
  ),
  new PersonajeModel(5, 
    "1913-06-26", 
    "2010-11-29", 
    "Maurice Wilkes", 
    "Británico", 
    "Figura clave en la historia de la computación, lideró el desarrollo de EDSAC, el primer computador de programa almacenado en operar de forma práctica y continua. Introdujo el concepto de microprogramación, esencial en el diseño de procesadores modernos, y fue coautor del primer libro sobre programación. También impulsó el uso de bibliotecas de subrutinas, el tiempo compartido y la memoria caché. Su enfoque práctico convirtió la computación en una herramienta accesible para científicos e investigadores, consolidando su legado como uno de los arquitectos del campo informático.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR28OhK409F1HXmYwZ4R04dyl89bcDIFIloWQ&s"
    ),
  new PersonajeModel(6,
    "1924-12-03", 
    "2007-03-17", 
    "John Backus", 
    "Estadounidense", 
    "FImpulsó una revolución en la forma en que los humanos se comunican con las computadoras al liderar la creación de Fortran, el primer lenguaje de programación de alto nivel ampliamente adoptado. También fue coautor del sistema formal Backus-Naur, base para describir la sintaxis de los lenguajes. Promotor del paradigma funcional, buscó formas más expresivas y eficientes de programar. Su enfoque innovador y su disposición a desafiar normas establecidas dejaron una huella perdurable en el desarrollo del software moderno.",
    "https://www.biografiasyvidas.com/biografia/b/fotos/backus.jpg"
    ),
  new PersonajeModel(7,
    "1927-09-04", 
    "2011-10-24", 
    "John McCarthy", 
    "Estadounidense", 
    "Fue una figura clave en el nacimiento de la inteligencia artificial, término que acuñó en 1956 al organizar la Conferencia de Dartmouth. Desarrolló el lenguaje de programación LISP, fundamental para la programación simbólica, y exploró la lógica formal como base para replicar el razonamiento humano. Su visión definió los pilares de la IA moderna, abriendo camino a sistemas capaces de simular el pensamiento. Su legado perdura en cada avance que busca dotar a las máquinas de inteligencia.",
    "https://imagenes.elpais.com/resizer/v2/ONU6VPSB4VG7WPAPRLSULT74XI.jpg?auth=7901c8ac1386dd991fcbd2441edadaa574db78eab3fb4a33fee6175583dd4edc&width=1960&height=1470&smart=true"
    ),
  new PersonajeModel(8,
    "1906-12-09", 
    "1992-01-01", 
    "Grace Hopper", 
    "Estadounidense", 
    "Pionera de la programación y oficial de la Marina de EE. UU. Obtuvo un doctorado en matemáticas por Yale y fue una de las primeras mujeres programadoras del Harvard Mark I durante la Segunda Guerra Mundial. Creó el primer compilador en 1952, lo que permitió traducir instrucciones escritas en inglés a código máquina, y lideró el desarrollo de FLOW-MATIC, el primer lenguaje que usaba comandos en inglés. Su trabajo fue clave en la creación de COBOL, un lenguaje orientado a negocios que revolucionó la informática al hacerla accesible a usuarios no técnicos. Fue una incansable promotora de lenguajes de programación “amigables” y una educadora apasionada. Se retiró como contralmirante, la oficial de mayor edad en servicio activo en la historia de EE. UU., y fue reconocida con la Medalla Nacional de Tecnología y la Medalla Presidencial de la Libertad. Su legado vive en la forma en que interactuamos con las computadoras hoy.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWxgK0aysd1BduMeJ24SyisOk-CqlCSSvhfQ&s"
  ),
  new PersonajeModel(9,
    "1926-05-31", 
    "1992-12-26", 
    "John Kemeny", 
    "Húngaro,Estadounidense", 
    "Matemático, educador y pionero en informática, reconocido por co-crear el lenguaje de programación BASIC junto a Thomas Kurtz, con el objetivo de hacer la programación accesible para todos, no solo científicos. También fue clave en la creación del sistema de tiempo compartido Dartmouth Time-Sharing System (DTSS), que permitió a múltiples usuarios usar un mismo ordenador de forma remota, anticipando el modelo de computación en red.",
    "https://www.azquotes.com/public/pictures/authors/df/1f/df1f81bae1533dbc37ba4d1a199f73fd/54757f5d7c104_john_g_kemeny.jpg"
  ),
  new PersonajeModel(9,
    "1928-02-22", 
    "2024-11-12", 
    "Thomas Kurtz", 
    "Estadounidense", 
    "Fue una figura clave en la creación de uno de los primeros lenguajes de programación accesibles para estudiantes, impulsando así la democratización del acceso a la computación. Junto a un colega, desarrolló un innovador sistema de tiempo compartido que permitió que múltiples usuarios interactuaran con una misma computadora desde diferentes terminales, una solución revolucionaria para su época. Su trayectoria combinó la docencia, la gestión académica y la estandarización del software, liderando iniciativas que definieron estándares internacionales. También participó en proyectos orientados a la educación informática y fundó una empresa dedicada a crear compiladores multiplataforma y software educativo.",
    "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQlAchdEM3VypeDB0BiGGdSJ86n80toEXmES955PRi06zcQeVrpQaaKIb3NlOil-jyRkvd9ceGaTI7LoYSDgp2JIQ"
  ),
  new PersonajeModel(10,
    "1931-10-12", 
    "2002-06-29", 
    "Ole-Johan Dahl", 
    "Noruego", 
    "Fue un pionero en el campo de la informática, reconocido principalmente por co-crear los primeros lenguajes de programación orientados a objetos, estableciendo conceptos fundamentales como clase, herencia, encapsulamiento y creación dinámica de objetos. Su trabajo revolucionó el diseño y desarrollo de software, facilitando la construcción de aplicaciones reutilizables, escalables y confiables. Además, fue el primer profesor de informática en su universidad, donde impulsó la investigación y la educación en esta disciplina emergente. Destacó por combinar un enfoque formal y riguroso con la aplicabilidad práctica, contribuyendo al avance de métodos formales y herramientas para la programación orientada a objetos.",
    "https://www.ub.uio.no/fag/informatikk/faglig/dns/bilder/dahlolejohan_cropped.jpeg"
),
  new PersonajeModel(10,
    "1926-08-27", 
    "2002-08-10", 
    "Kristen Nygaard", 
    "Noruego", 
    "Fue un destacado pionero en informática, co-creador junto a un colega del paradigma de programación orientada a objetos a través del desarrollo de los lenguajes Simula I y Simula 67. Introdujo conceptos esenciales como clase, herencia, encapsulamiento y creación dinámica de objetos, que transformaron radicalmente el diseño y la construcción de software, promoviendo aplicaciones más reutilizables, confiables y escalables. Su legado es la base de lenguajes orientados a objetos ampliamente usados hoy en día, como C++ y Java. Además, tuvo una carrera académica dedicada a la enseñanza y promoción de la informática en su universidad.",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhVw6YVlGjD1TbbSyzuEyXrIrfHdSY0sChZ48bcTBQlXwBskze0YSI-H8EIftQ_ikTP0gdQetssB_Go3jZpVifF9mjHVdlMWKJRglBQ3hiMrX_xJm_0avlxLveECJqIqofgZAgALFFnc5U/s1600/08-27+Efemerides+de+Tecnologia+kristen_nygaard.jpg"
  ),
  new PersonajeModel(11,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un pionero en la informática, co-desarrollando el sistema operativo Unix y creando el lenguaje C, que se convirtieron en fundamentos clave para el software moderno. Su trabajo permitió que los programas fueran portables y eficientes, influyendo en lenguajes posteriores como C++ y Java. Además, impulsó la colaboración entre programadores y participó en proyectos innovadores de sistemas operativos. Recibió múltiples reconocimientos, incluyendo el Premio Turing, y se le recuerda por su claridad, modestia y sentido del humor.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(11,
    "1943-02-04", 
    "Aun Esta Vivo con 82 años", 
    "Ken Thompson", 
    "Estadounidense", 
    "Fue co-creador del sistema operativo UNIX, diseñado inicialmente como una versión simplificada de un sistema más grande para adaptarse a las nuevas minicomputadoras de finales de los años 60. Gracias a la reescritura en lenguaje C, UNIX se convirtió en un sistema portátil y ampliamente utilizado en diversas plataformas, desde supercomputadoras hasta dispositivos móviles y sistemas críticos. Su diseño ha asegurado la longevidad, confiabilidad y seguridad que caracterizan a UNIX y sus variantes. Fue galardonado con premios prestigiosos, incluyendo el Premio Turing y la Medalla Nacional de Tecnología, en reconocimiento a su impacto duradero en la informática.",
    "https://twimgs.com/informationweek/1304/304Dobbs_Thompson.jpg"
),
  new PersonajeModel(12,
    "1934-02-15", 
    "2024-01-01", 
    "Niklaus Wirth", 
    "Suizo", 
    "Fue un influyente científico de la computación, conocido principalmente por diseñar el lenguaje de programación Pascal, además de crear ALGOL-W y Modula-2. Defensor de la programación estructurada, promovió la simplicidad y la disciplina en el diseño de software, enfatizando la importancia de descomponer problemas en partes más pequeñas para facilitar la escritura y mantenimiento del código. Su trabajo influyó en numerosos lenguajes posteriores y en la enseñanza de la programación. También contribuyó al desarrollo del teclado moderno, introduciendo la tecla Alt para ampliar las combinaciones de comandos. Fue profesor y líder académico, recibiendo premios destacados como el Premio Turing.",
    "https://www.comp.hkbu.edu.hk/dlecture/wirth/img/niklaus_wirth.jpg"
  ),
  new PersonajeModel(13,
    "1941-09-09", 
    "2011-10-12", 
    "Dennis Ritchie", 
    "Estadounidense", 
    "Fue un pionero en la informática, co-desarrollando el sistema operativo Unix y creando el lenguaje C, que se convirtieron en fundamentos clave para el software moderno. Su trabajo permitió que los programas fueran portables y eficientes, influyendo en lenguajes posteriores como C++ y Java. Además, impulsó la colaboración entre programadores y participó en proyectos innovadores de sistemas operativos. Recibió múltiples reconocimientos, incluyendo el Premio Turing, y se le recuerda por su claridad, modestia y sentido del humor.",
    "https://s3.amazonaws.com/media.thecrimson.com/photos/2013/05/27/213905_1288084.jpg"
  ),
  new PersonajeModel(14,
    "1947-02-08", 
    "Aun Esta Vivo con 78 años", 
    "Gerald Jay Sussman", 
    "Estadounidense", 
    "Es un destacado investigador y profesor en ingeniería eléctrica, especializado en inteligencia artificial, lenguajes de programación y educación en ciencias de la computación. Su trabajo ha formalizado y automatizado estrategias para la resolución de problemas científicos y de ingeniería, mejorando la enseñanza mediante métodos computacionales. Fue coautor de un influyente libro de introducción a la programación y co-inventor del lenguaje Scheme. También desarrolló herramientas de diseño asistido por computadora para simulaciones avanzadas y contribuyó en la ingeniería de telescopios profesionales. Es miembro de varias asociaciones científicas y tecnológicas de prestigio.",
    "https://i.ytimg.com/vi/Tdwr9tweTDE/maxresdefault.jpg"
  ),
  new PersonajeModel(14,
    "1954-10-02", 
    "Aun Esta Vivo con 71 años", 
    "Guy L. Steele Jr.", 
    "Estadounidense", 
    "reconocido arquitecto de software con formación en Harvard y MIT, que ha trabajado en empresas como Sun Microsystems y Oracle Labs, además de enseñar en Carnegie Mellon. Coautor de varios libros influyentes, fue clave en la definición del dialecto Scheme de Lisp y ha contribuido en el desarrollo y estandarización de lenguajes como C, Fortran, Common Lisp y Java. También lideró el diseño de Fortress, un lenguaje orientado a objetos para computación de alto rendimiento. Ha recibido premios importantes en el campo de los lenguajes de programación y es miembro de varias academias y comités de estandarización.",
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT_Ywoq1EYce2xGqPhaVwSJcvAsY9oUu3Z7B1Mb5hM6vgdVN5Vo"
  ),
  new PersonajeModel(15,
    "1940-05-17", 
    "Aun Esta Vivo con 85 años", 
    "Alan Kay", 
    "Estadounidense", 
    "Fue un pionero de la computación conocido por crear el lenguaje de programación Smalltalk y desarrollar conceptos clave de la programación orientada a objetos. Su trabajo en Xerox PARC impulsó avances como las interfaces gráficas de usuario, la arquitectura cliente-servidor y tecnologías como Ethernet y la publicación digital. También diseñó la idea del Dynabook, precursor de las laptops modernas, y ha tenido roles importantes en Atari, Apple, Disney y Hewlett Packard. Fundador de un instituto de investigación, ha recibido numerosos premios prestigiosos, incluido el Turing Award.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs69fVAskz54mJLtdG_okcgDmeAlZX28B9Nw&s"
  ),
  new PersonajeModel(16,
    "1950-12-30", 
    "Aun Esta Vivo con 74 años", 
    "Bjarne Stroustrup", 
    "Danés", 
    "Es el creador de C++, el primer lenguaje orientado a objetos ampliamente utilizado, desarrollado como una extensión del lenguaje C durante su trabajo en Bell Labs. Obtuvo su doctorado en Cambridge en 1979 y combinó la eficiencia de C con características orientadas a objetos para facilitar la programación en sistemas distribuidos. Su libro sobre C++ y su esfuerzo por estandarizar el lenguaje contribuyeron a su popularidad, aunque C++ es conocido por su complejidad y posibilidad de errores, características que Stroustrup defendió como necesarias para usuarios avanzados. Fue profesor en Texas A&M y Columbia, trabajó en Morgan Stanley, y recibió numerosos premios, entre ellos el Grace Murray Hopper Award y el Charles Stark Draper Prize. Está casado, tiene dos hijos y vive en Nueva York cerca de su familia.",
    "https://www.ull.es/portal/noticias/wp-content/uploads/sites/13/2025/02/bjarne-stroustrup.jpeg"
  ),
  new PersonajeModel(17,
    "1954-09-27", 
    "Aun Esta Vivo con 70 años", 
    "Larry Wall", 
    "Estadounidense", 
    "Larry Wall creó Perl en 1987 mientras trabajaba en Unisys, desarrollando un lenguaje dinámico y flexible usado en múltiples sistemas operativos y áreas como CGI y administración de sistemas. Perl 5 introdujo objetos y módulos, permitiendo extensiones sin cambiar el intérprete, y Perl 6 (luego Raku) se volvió un lenguaje aparte. Con formación en lingüística, Wall incorporó conceptos del lenguaje natural en Perl y promovió que las tareas fáciles sean simples y las difíciles posibles. También creó herramientas clave para Unix, como el cliente de noticias rn y el programa patch. Su fe cristiana influyó en la terminología de Perl, y es conocido por su humor y gran aceptación en la comunidad informática.",
    "https://www.perl.com/images/listen-to-larry-wall-s-state-of-the-onion-2000-on-youtube/larry-wall.jpg"
  ),
  new PersonajeModel(18,
    "1956-01-31", 
    "Aun Esta Vivo con 69 años", 
    "Guido Van Rossum", 
    "Neerlandés", 
    "Guido van Rossum creó Python en 1991 como un lenguaje de programación de alto nivel, multiparadigma y fácil de entender, inspirado en el lenguaje educativo ABC pero con mayor extensibilidad y enfoque en la simplicidad. Aunque inicialmente fue un proyecto personal sin pensar en aplicaciones prácticas, Python se volvió muy popular en internet, inteligencia artificial y seguridad informática, siendo usado por empresas como Google y Spotify. Van Rossum promovió la cultura open source y la comunidad Python, guiando su desarrollo como “Benevolent Dictator for Life” hasta 2018. También trabajó en proyectos clave en Google y Microsoft, impulsando mejoras en Python. Su influencia incluye la introducción de procesos formales de propuestas para cambios en el lenguaje y una filosofía que prioriza el código claro y natural, reflejada en la comunidad y en el nombre del lenguaje, inspirado en Monty Python.",
    "https://gvanrossum.github.io/images/guido-headshot-2019.jpg"
  ),
  new PersonajeModel(19,
    "1952-06-03", 
    "Aun Esta Vivo con 73 años", 
    "Alan Cooper", 
    "Estadounidense", 
    "Alan Cooper es reconocido por haber creado el entorno de desarrollo visual que dio origen a Visual BASIC, cuya interfaz revolucionó la programación al facilitar la creación de aplicaciones mediante herramientas gráficas. Su trabajo fue clave para Microsoft, y por ello es conocido como el padre de Visual BASIC. Posteriormente fundó Cooper Interaction Design, donde introdujo conceptos fundamentales para la experiencia de usuario como personas, escenarios y diseño orientado a objetivos, estableciendo las bases del campo del diseño de interacción. También es autor de libros influyentes en esta área y ha sido premiado por sus contribuciones al desarrollo de software.",
    "https://miro.medium.com/v2/resize:fit:2400/1*Wnmk3ItpT_6cKeQUSlc5hg.jpeg"
  ),
  new PersonajeModel(20,
    "1955-05-19", 
    "Aun Esta Vivo con 70 años", 
    "James Gosling", 
    "Canadiense", 
    "Es conocido como el creador de Java, un lenguaje de programación desarrollado en Sun Microsystems durante los años noventa que revolucionó la informática al permitir que programas pudieran ejecutarse en múltiples plataformas sin modificaciones gracias al uso de máquinas virtuales. Originalmente diseñado para aplicaciones de televisión interactiva, Java encontró su verdadero potencial con el auge de la web, donde su portabilidad y facilidad de uso lo convirtieron en un estándar para aplicaciones en línea. Antes de Java, Gosling ya había contribuido al desarrollo de herramientas como Gosling Emacs y el sistema de ventanas NeWS. Tras la adquisición de Sun por Oracle, dejó la empresa por desacuerdos con su nueva gestión. Luego trabajó en Google, en robótica marina con Liquid Robotics, y más adelante en Amazon Web Services, además de participar como asesor en varias compañías tecnológicas.",
    "https://www.sis.pitt.edu/mbsclass/hall_of_fame/images/gosling.jpg"
  ),
  new PersonajeModel(21,
    "1961-07-04", 
    "Aun Esta Vivo con 64 años", 
    "Brendan Eich", 
    "Estadounidense", 
    "Creador de JavaScript y cofundador del proyecto Mozilla. Tras obtener títulos en matemáticas y ciencias de la computación, trabajó en Silicon Graphics antes de unirse a Netscape en 1995, donde desarrolló JavaScript en apenas diez días como un lenguaje que combinaba la sintaxis de Java con características funcionales de Scheme. También creó el motor SpiderMonkey para ejecutar JavaScript en el navegador Netscape Navigator. JavaScript se convirtió en un lenguaje clave del desarrollo web por su tipado dinámico, orientación a objetos basada en prototipos y soporte para múltiples paradigmas de programación. Su ejecución en el lado del cliente lo hace eficiente y accesible, y su capacidad de integrarse con otros lenguajes lo ha consolidado como una herramienta esencial para crear contenido dinámico en la web.",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Brendan_Eich_Mozilla_Foundation_official_photo.jpg/1200px-Brendan_Eich_Mozilla_Foundation_official_photo.jpg"
),
  new PersonajeModel(22,
    "1968-11-22", 
    "Aun Esta Vivo con 56 años", 
    "Rasmus Lerdorf", 
    "Groenlandés, Canadiense", 
    "Creador de PHP en 1995 como una herramienta personal para gestionar su sitio web, sin imaginar que se convertiría en uno de los lenguajes más utilizados en la creación de sitios dinámicos, incluyendo plataformas como WordPress. Inicialmente basado en scripts Perl y luego reescrito en C como PHP/FI, permitía integrar HTML, manejar formularios y construir aplicaciones web básicas. Además de continuar colaborando con el desarrollo de PHP, Lerdorf ha trabajado en empresas como IBM, Yahoo! y Etsy, y ha contribuido a proyectos clave como el servidor Apache y la base de datos MySQL. Aunque se considera más un solucionador de problemas que un programador, ha sido una figura central en la evolución del software de código abierto y de la web moderna.",
    "https://pbs.twimg.com/profile_images/918348833205116928/V9ROYRNJ_400x400.jpg"
),
  new PersonajeModel(23,
    "1965-04-14", 
    "Aun Esta Vivo con 60 años", 
    "Yukihiro Matsumoto", 
    "Japonés", 
    "Tambien conocido como Matz, es el creador del lenguaje de programación Ruby y de su primera implementación oficial, Matz’s Ruby Interpreter (MRI). Diseñó Ruby con el objetivo de lograr un equilibrio entre la funcionalidad y la felicidad del programador, promoviendo un enfoque centrado en la simplicidad y la productividad. Su trabajo ha influido en la comunidad de desarrollo por su filosofía orientada a objetos y su sintaxis clara. Además de liderar el desarrollo de Ruby, ha ocupado cargos como arquitecto jefe de Ruby en Heroku y ha sido investigador en el Rakuten Institute of Technology, así como asesor técnico en empresas tecnológicas en Japón.",
    "https://siliconangle.com/files/2011/08/matz.jpg"
),
  new PersonajeModel(24,
    "2001", 
    "",
    "Creadores del Manifiesto Ágil", 
    "Diversas nacionalidades", 
    "Fueron 17 expertos en desarrollo de software que se reunieron en 2001 en Snowbird, Utah, para definir un conjunto de valores y principios que dieran lugar al Manifiesto Ágil. Este documento revolucionó la forma en que se desarrollan proyectos de software, promoviendo la colaboración, la flexibilidad, la entrega continua y la respuesta al cambio.",
    "https://cloudfront.codeproject.com/architecture/1064114/000.jpg"
),
  new PersonajeModel(25,
    "1960-12-02", 
    "Aun Esta Vivo con 64 años", 
    "Anders Hejlsberg", 
    "Danés", 
    "Conocido por crear Turbo Pascal y liderar el desarrollo de Delphi y C#, fue pionero en herramientas de desarrollo que simplificaron y aceleraron la creación de software. En sus inicios desarrolló compiladores de Pascal para computadoras personales, lo que llevó a la integración de un entorno completo de programación que revolucionó el acceso a herramientas profesionales. En Borland impulsó Delphi, entorno que introdujo el desarrollo visual y la conexión directa a bases de datos, marcando el inicio del desarrollo rápido de aplicaciones (RAD). Luego, en Microsoft, lideró la creación de C#, un lenguaje moderno, orientado a objetos y parte clave de la plataforma .NET. C# combina lo mejor de lenguajes anteriores con características como recolección de basura, seguridad de tipos, portabilidad y eficiencia, facilitando el desarrollo de aplicaciones de todo tipo.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Xqw_fCI9vzOM05YxBYhWH60VULyhSHkyA&s"
),
  new PersonajeModel(26,
    "1979-10-15", 
    "Aun Esta Vivo con 45 años", 
    "David Heinemeier Hansson", 
    "Danés", 
    "Creador de Ruby on Rails, un influyente framework de desarrollo web utilizado por empresas como GitHub, Shopify y Airbnb. Es copropietario de 37signals, compañía detrás de productos como Basecamp, HEY y ONCE, centrados en software simple y eficiente sin depender de suscripciones. Ha coescrito libros sobre cómo dirigir empresas de forma más calmada y productiva, incluyendo éxitos como REWORK y REMOTE. Además, ha competido profesionalmente en automovilismo, ganando su categoría en Le Mans y participando en múltiples campeonatos internacionales. También mantiene una activa presencia en medios, escritura y tecnología.",
    "https://images.squarespace-cdn.com/content/v1/61a2ba6209495b7cde63e740/f0146386-1933-495b-aa8e-97d325a7ec23/David+Heinemeier+Hansson.jpg"
),
  new PersonajeModel(27,
    "1955-02-24", 
    "2011-10-05", 
    "Steve Jobs", 
    "Estadounidense", 
    "Fue uno de los responsables de transformar la industria tecnológica con productos innovadores como el iPhone, el iPad y el iPod. Cofundó una empresa desde un garaje y la convirtió en una de las más valiosas del mundo, revolucionando el diseño y la experiencia del usuario. Impulsó Pixar como pionera en la animación digital, invirtió en tecnologías avanzadas y regresó a liderar la compañía que él mismo había dejado, revitalizándola por completo. Su visión combinó estética, funcionalidad y estrategia de negocio. En sus últimos años enfrentó desafíos de salud mientras continuaba influyendo decisivamente en el rumbo de la tecnología moderna.",
    "https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/13873773/stevejobs.1419962519.png?quality=90&strip=all&crop=0,13.457556935818,100,73.084886128364"
),
new PersonajeModel(28,
    "1981-01-22", 
    "Actualmente vivo", 
    "Ryan Dahl", 
    "Estadounidense", 
    "Ingeniero de software reconocido por haber creado el entorno de ejecución Node.js. Creció en San Diego, donde desde pequeño tuvo contacto con la tecnología gracias a un Apple II que le regalaron. Estudió matemáticas en la Universidad de California en San Diego y posteriormente en la Universidad de Rochester, donde inició un doctorado en topología algebraica, pero lo abandonó para dedicarse a la programación web. Tras desarrollar Node.js desde 2009, se retiró del proyecto en 2012 para enfocarse en otros proyectos de investigación, aunque continuó asesorando a Joyent, empresa vinculada a Node.js. Más tarde, apoyó y recomendó Node.js incluso para aplicaciones críticas.",
    "https://cdn.cloudinary.com/stichting-frontend-amsterdam/image/upload/v1674813354/dev/Dahl_Ryan_wg0lg5.png"
),
  new PersonajeModel(29,
    "1979-05-27", 
    "Actualmente vivo", 
    "Tom Preston-Werner", 
    "Estadounidense", 
    "Desarrollador de software y empresario conocido por cofundar GitHub, plataforma líder para el desarrollo colaborativo y control de versiones. Creó además Gravatar, Jekyll, TOML y la especificación de versionado semántico, herramientas que han tenido gran impacto en la comunidad tecnológica. Tras vender Gravatar y rechazar una oferta de Microsoft, se enfocó en sus propios proyectos y lideró GitHub como CEO, transformando la forma en que los desarrolladores colaboran globalmente. Actualmente reside en San Francisco y, junto a su esposa, está comprometido con importantes causas filantrópicas.",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWad4zCbYGj0rjz67xLkzkD5mU6S5bQS0CNw&s"
),
  new PersonajeModel(30,
    "1978-06-30", 
    "Actualmente vivo", 
    "Chris Lattner", 
    "Estadounidense", 
    "Es un destacado constructor de sistemas y experto en compiladores de código abierto, conocido por crear y escalar infraestructuras como LLVM, Clang, MLIR y CIRCT, que son fundamentales para tecnologías como iOS, Android, CUDA y TensorFlow. Fundador y CEO de Modular AI, lidera el desarrollo de infraestructura avanzada para inteligencia artificial. Fue creador y líder del lenguaje de programación Swift. Ha trabajado en proyectos clave en Google, Tesla, Apple y SiFive, donde impulsó productos y equipos de ingeniería a nivel global. Su trabajo en MLIR redefinió el diseño de compiladores con un enfoque innovador adoptado por grandes empresas y proyectos industriales. Además, promovió herramientas interactivas para facilitar el aprendizaje y la adopción de Swift, con el objetivo de transformar la educación en ciencias de la computación.",
    "https://www.nondot.org/sabre/img/ChrisPhoto5.jpg"
),
new PersonajeModel(31,
  "1960-12-02", 
  "Aun Esta Vivo con 64 años", 
  "Anders Hejlsberg", 
  "Danés", 
  "Conocido por crear Turbo Pascal y liderar el desarrollo de Delphi y C#, fue pionero en herramientas de desarrollo que simplificaron y aceleraron la creación de software. En sus inicios desarrolló compiladores de Pascal para computadoras personales, lo que llevó a la integración de un entorno completo de programación que revolucionó el acceso a herramientas profesionales. En Borland impulsó Delphi, entorno que introdujo el desarrollo visual y la conexión directa a bases de datos, marcando el inicio del desarrollo rápido de aplicaciones (RAD). Luego, en Microsoft, lideró la creación de C#, un lenguaje moderno, orientado a objetos y parte clave de la plataforma .NET. C# combina lo mejor de lenguajes anteriores con características como recolección de basura, seguridad de tipos, portabilidad y eficiencia, facilitando el desarrollo de aplicaciones de todo tipo.",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Xqw_fCI9vzOM05YxBYhWH60VULyhSHkyA&s"
),
  new PersonajeModel(32,
    "1984-08-05", 
    "Actualmente vivo", 
    "Jordan Walke", 
    "Estadounidense", 
    "Ingeniero de software reconocido por crear React, una biblioteca de JavaScript que revolucionó el desarrollo de interfaces de usuario con su arquitectura basada en componentes y el uso del DOM virtual, simplificando la construcción de aplicaciones web eficientes. Tras graduarse en MIT, trabajó en Facebook, donde lanzó React en 2011, que rápidamente se convirtió en un estándar de la industria. Su liderazgo técnico y visión han influido profundamente en el desarrollo web moderno, promoviendo la simplicidad, eficiencia y un enfoque en el aprendizaje continuo, además de fomentar una cultura que valora la resiliencia ante los desafíos tecnológicos.",
    "https://media.licdn.com/dms/image/v2/D4E03AQF4wHiGZObs0g/profile-displayphoto-shrink_200_200/B4EZZpHJM1HoAg-/0/1745520203877?e=2147483647&v=beta&t=1uF6EPQD8JW6YETHihWLJ1g5bwlicuQMV17Smqu_mEk"
),
  new PersonajeModel(33,
    "1973", 
    "Actualmente vivo", 
    "Graydon Hoare", 
    "Canadiense", 
    "Ingeniero de lenguajes de programación y experto en compiladores que comenzó Rust como un proyecto personal motivado por su pasión por resolver problemas complejos de concurrencia y seguridad en la programación. Su diseño innovador de Rust, basado en un modelo de propiedad y control de acceso a datos que garantiza seguridad sin afectar el rendimiento, ha revolucionado el desarrollo de software concurrente. Antes de crear Rust, trabajó en proyectos importantes como GCC, Clang y Swift, y su enfoque apasionado y experimental lo llevó a crear un lenguaje que hoy es ampliamente reconocido por su robustez y eficiencia.",
    "https://images.crunchbase.com/image/upload/c_thumb,h_256,w_256,f_auto,g_face,z_0.7,q_auto:eco,dpr_1/ywecf1vqgwj0abhbwskb"
),
  new PersonajeModel(35,
    "1980", 
    "Actualmente vivo", 
    "Luke Wagner", 
    "Estadounidense", 
    "Ingeniero destacado que trabaja en Fastly dentro del equipo de Investigación y Tecnologías Emergentes, centrado en el desarrollo y evolución de los estándares de WebAssembly. También co-preside el grupo de trabajo de WebAssembly en el W3C, impulsando propuestas y colaborando con múltiples empresas para avanzar en esta tecnología. Cuenta con amplia experiencia en proyectos relacionados con navegadores y tecnologías web.",
    "https://www.fastly.com/cimages/ocb1q9kflo7k/2xiIWWRVolxPBc40EMvCy6/29ba25f3f237069a5790aa8bd21dd933/image-20240227-202107.png?auto=avif&crop=1:1,smart&width=288"
),
  new PersonajeModel(37,
    "1990", 
    "Actualmente vivo", 
    "Jarred Sumner", 
    "Estadounidense", 
    "Ingeniero con amplia experiencia en tecnología, desarrollo de software y emprendimiento. Actualmente lidera una empresa enfocada en aplicaciones web y móviles con más de 5 millones de usuarios en más de 15 países. Ha trabajado en roles clave como ingeniero de front-end y de producto en empresas reconocidas del sector tecnológico. Su carrera comenzó temprano y ha participado en proyectos fundamentales de desarrollo de comercio electrónico y mejora de experiencia de usuario, además de gestionar proyectos freelance y desarrollo de productos para diversas compañías.",
    "https://pbs.twimg.com/profile_images/1342417825483300864/Vz4ChOFG_400x400.jpg"
),
  new PersonajeModel(38,
    "1980", 
    "Actualmente vivo", 
    "Rich Harris", 
    "Estadounidense", 
    "Comenzó su carrera en el periodismo, donde descubrió el potencial de las tecnologías web para enriquecer la narrativa mediante visualizaciones de datos. Esta curiosidad lo llevó a aprender JavaScript y desarrollar herramientas propias, que luego compartió como software de código abierto. Con el tiempo, creó un innovador framework de interfaz llamado Svelte, seguido por SvelteKit, orientado a facilitar el desarrollo de aplicaciones web modernas. Su trabajo se caracteriza por priorizar la experiencia del desarrollador, mejorar el rendimiento y buscar un equilibrio eficiente entre tareas del cliente y del servidor.",
    "https://avatars.githubusercontent.com/u/1162160?v=4"
),
  new PersonajeModel(39,
    "", 
    "", 
    "Comunidad open source", 
    "", 
    "Rust y WASM son elegidos para entornos de nube por su seguridad, eficiencia y portabilidad. Se usan cada vez más en microservicios, edge computing y entornos con recursos limitados.",
    "https://cdn.thenewstack.io/media/2021/09/480a814f-rust-wasm.png"
)

]);

export const seleccionarPersonaje = (IdPersonajes: number[]): void => {
  const personaje: PersonajeModel[] = get(personajesStore);
  personajeSeleccionado.set(personaje.filter(personaje => IdPersonajes.includes(personaje.IdPersonaje)));
};